// GENERATED by scripts/generate-db-types.ts — do not edit by hand.
// Format-compatible with `supabase gen types typescript`.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '12.2.3'
  }
  public: {
    Tables: {
      accounts: {
        Row: {
          id: string
          space_id: string
          name: string
          type: string
          opening_balance_cents: number
          owner_id: string | null
          is_active: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          name: string
          type: string
          opening_balance_cents?: number
          owner_id?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          name?: string
          type?: string
          opening_balance_cents?: number
          owner_id?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'accounts_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'accounts_space_id_owner_id_fkey'
            columns: ['space_id', 'owner_id']
            isOneToOne: false
            referencedRelation: 'financial_space_members'
            referencedColumns: ['space_id', 'user_id']
          },
        ]
      }
      ai_usage_events: {
        Row: {
          id: number
          user_id: string | null
          space_id: string | null
          operation: string
          provider: string
          model: string
          input_tokens: number | null
          output_tokens: number | null
          audio_seconds: number | null
          estimated_cost_usd_micros: number | null
          latency_ms: number | null
          success: boolean
          correlation_id: string | null
          created_at: string
        }
        Insert: {
          user_id?: string | null
          space_id?: string | null
          operation: string
          provider: string
          model: string
          input_tokens?: number | null
          output_tokens?: number | null
          audio_seconds?: number | null
          estimated_cost_usd_micros?: number | null
          latency_ms?: number | null
          success: boolean
          correlation_id?: string | null
          created_at?: string
        }
        Update: {
          user_id?: string | null
          space_id?: string | null
          operation?: string
          provider?: string
          model?: string
          input_tokens?: number | null
          output_tokens?: number | null
          audio_seconds?: number | null
          estimated_cost_usd_micros?: number | null
          latency_ms?: number | null
          success?: boolean
          correlation_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ai_usage_events_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'ai_usage_events_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      audit_log: {
        Row: {
          id: number
          space_id: string | null
          actor_id: string | null
          action: string
          entity_type: string
          entity_id: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          space_id?: string | null
          actor_id?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          space_id?: string | null
          actor_id?: string | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'audit_log_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'audit_log_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
        ]
      }
      cards: {
        Row: {
          id: string
          space_id: string
          name: string
          last_four: string | null
          closing_day: number
          due_day: number
          limit_cents: number | null
          holder_id: string | null
          tone: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          name: string
          last_four?: string | null
          closing_day: number
          due_day: number
          limit_cents?: number | null
          holder_id?: string | null
          tone?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          name?: string
          last_four?: string | null
          closing_day?: number
          due_day?: number
          limit_cents?: number | null
          holder_id?: string | null
          tone?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'cards_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'cards_space_id_holder_id_fkey'
            columns: ['space_id', 'holder_id']
            isOneToOne: false
            referencedRelation: 'financial_space_members'
            referencedColumns: ['space_id', 'user_id']
          },
        ]
      }
      categories: {
        Row: {
          id: string
          space_id: string
          group_id: string | null
          system_key: string | null
          name: string
          kind: string
          icon: string | null
          tone: string | null
          is_active: boolean
          is_system: boolean
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          group_id?: string | null
          system_key?: string | null
          name: string
          kind: string
          icon?: string | null
          tone?: string | null
          is_active?: boolean
          is_system?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          group_id?: string | null
          system_key?: string | null
          name?: string
          kind?: string
          icon?: string | null
          tone?: string | null
          is_active?: boolean
          is_system?: boolean
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'categories_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'categories_space_id_group_id_fkey'
            columns: ['space_id', 'group_id']
            isOneToOne: false
            referencedRelation: 'category_groups'
            referencedColumns: ['space_id', 'id']
          },
        ]
      }
      category_groups: {
        Row: {
          id: string
          space_id: string
          key: string | null
          name: string
          tone: string
          is_savings: boolean
          is_system: boolean
          sort_order: number
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          key?: string | null
          name: string
          tone?: string
          is_savings?: boolean
          is_system?: boolean
          sort_order?: number
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          key?: string | null
          name?: string
          tone?: string
          is_savings?: boolean
          is_system?: boolean
          sort_order?: number
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'category_groups_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
        ]
      }
      financial_space_members: {
        Row: {
          space_id: string
          user_id: string
          role: string
          status: string
          joined_at: string
          removed_at: string | null
        }
        Insert: {
          space_id: string
          user_id: string
          role: string
          status?: string
          joined_at?: string
          removed_at?: string | null
        }
        Update: {
          space_id?: string
          user_id?: string
          role?: string
          status?: string
          joined_at?: string
          removed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'financial_space_members_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'financial_space_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      financial_spaces: {
        Row: {
          id: string
          name: string
          type: string
          currency: string
          timezone: string
          plan_code: string
          owner_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          type: string
          currency?: string
          timezone?: string
          plan_code?: string
          owner_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          type?: string
          currency?: string
          timezone?: string
          plan_code?: string
          owner_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'financial_spaces_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'financial_spaces_plan_code_fkey'
            columns: ['plan_code']
            isOneToOne: false
            referencedRelation: 'plans'
            referencedColumns: ['code']
          },
        ]
      }
      goal_contributions: {
        Row: {
          id: string
          goal_id: string
          space_id: string
          amount_cents: number
          contributed_on: string
          note: string | null
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          goal_id: string
          space_id: string
          amount_cents: number
          contributed_on: string
          note?: string | null
          created_by: string
          created_at?: string
        }
        Update: {
          id?: string
          goal_id?: string
          space_id?: string
          amount_cents?: number
          contributed_on?: string
          note?: string | null
          created_by?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'goal_contributions_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'goal_contributions_space_id_goal_id_fkey'
            columns: ['space_id', 'goal_id']
            isOneToOne: false
            referencedRelation: 'goals'
            referencedColumns: ['space_id', 'id']
          },
        ]
      }
      goals: {
        Row: {
          id: string
          space_id: string
          name: string
          target_amount_cents: number
          target_date: string | null
          status: string
          scope: string
          owner_id: string | null
          tone: string
          created_by: string
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          name: string
          target_amount_cents: number
          target_date?: string | null
          status?: string
          scope?: string
          owner_id?: string | null
          tone?: string
          created_by: string
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          name?: string
          target_amount_cents?: number
          target_date?: string | null
          status?: string
          scope?: string
          owner_id?: string | null
          tone?: string
          created_by?: string
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'goals_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'goals_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'goals_space_id_owner_id_fkey'
            columns: ['space_id', 'owner_id']
            isOneToOne: false
            referencedRelation: 'financial_space_members'
            referencedColumns: ['space_id', 'user_id']
          },
        ]
      }
      monthly_plans: {
        Row: {
          id: string
          space_id: string
          month: string
          expected_income_cents: number
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          month: string
          expected_income_cents?: number
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          month?: string
          expected_income_cents?: number
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'monthly_plans_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'monthly_plans_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
        ]
      }
      plan_category_budgets: {
        Row: {
          plan_id: string
          space_id: string
          category_id: string
          amount_cents: number
        }
        Insert: {
          plan_id: string
          space_id: string
          category_id: string
          amount_cents: number
        }
        Update: {
          plan_id?: string
          space_id?: string
          category_id?: string
          amount_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: 'plan_category_budgets_space_id_category_id_fkey'
            columns: ['space_id', 'category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'plan_category_budgets_space_id_plan_id_fkey'
            columns: ['space_id', 'plan_id']
            isOneToOne: false
            referencedRelation: 'monthly_plans'
            referencedColumns: ['space_id', 'id']
          },
        ]
      }
      plan_group_budgets: {
        Row: {
          plan_id: string
          space_id: string
          group_id: string
          mode: string
          percent_bp: number | null
          amount_cents: number | null
        }
        Insert: {
          plan_id: string
          space_id: string
          group_id: string
          mode: string
          percent_bp?: number | null
          amount_cents?: number | null
        }
        Update: {
          plan_id?: string
          space_id?: string
          group_id?: string
          mode?: string
          percent_bp?: number | null
          amount_cents?: number | null
        }
        Relationships: [
          {
            foreignKeyName: 'plan_group_budgets_space_id_group_id_fkey'
            columns: ['space_id', 'group_id']
            isOneToOne: false
            referencedRelation: 'category_groups'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'plan_group_budgets_space_id_plan_id_fkey'
            columns: ['space_id', 'plan_id']
            isOneToOne: false
            referencedRelation: 'monthly_plans'
            referencedColumns: ['space_id', 'id']
          },
        ]
      }
      plans: {
        Row: {
          code: string
          name: string
          max_members: number
          ai_actions_per_month: number
          history_months: number | null
          max_recurring_rules: number | null
          created_at: string
        }
        Insert: {
          code: string
          name: string
          max_members: number
          ai_actions_per_month: number
          history_months?: number | null
          max_recurring_rules?: number | null
          created_at?: string
        }
        Update: {
          code?: string
          name?: string
          max_members?: number
          ai_actions_per_month?: number
          history_months?: number | null
          max_recurring_rules?: number | null
          created_at?: string
        }
        Relationships: [
        ]
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          timezone: string
          currency: string
          locale: string
          default_space_id: string | null
          onboarded_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          timezone?: string
          currency?: string
          locale?: string
          default_space_id?: string | null
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          timezone?: string
          currency?: string
          locale?: string
          default_space_id?: string | null
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_default_space_fk'
            columns: ['default_space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
        ]
      }
      recurring_rules: {
        Row: {
          id: string
          space_id: string
          type: string
          description: string
          amount_cents: number
          category_id: string | null
          account_id: string | null
          card_id: string | null
          member_id: string
          scope: string
          frequency: string
          interval: number
          start_on: string
          next_occurrence_on: string
          end_on: string | null
          is_active: boolean
          auto_post: boolean
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          type: string
          description: string
          amount_cents: number
          category_id?: string | null
          account_id?: string | null
          card_id?: string | null
          member_id: string
          scope?: string
          frequency: string
          interval?: number
          start_on: string
          next_occurrence_on: string
          end_on?: string | null
          is_active?: boolean
          auto_post?: boolean
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          type?: string
          description?: string
          amount_cents?: number
          category_id?: string | null
          account_id?: string | null
          card_id?: string | null
          member_id?: string
          scope?: string
          frequency?: string
          interval?: number
          start_on?: string
          next_occurrence_on?: string
          end_on?: string | null
          is_active?: boolean
          auto_post?: boolean
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'recurring_rules_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'recurring_rules_space_id_account_id_fkey'
            columns: ['space_id', 'account_id']
            isOneToOne: false
            referencedRelation: 'accounts'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'recurring_rules_space_id_card_id_fkey'
            columns: ['space_id', 'card_id']
            isOneToOne: false
            referencedRelation: 'cards'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'recurring_rules_space_id_category_id_fkey'
            columns: ['space_id', 'category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'recurring_rules_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'recurring_rules_space_id_member_id_fkey'
            columns: ['space_id', 'member_id']
            isOneToOne: false
            referencedRelation: 'financial_space_members'
            referencedColumns: ['space_id', 'user_id']
          },
        ]
      }
      space_invitations: {
        Row: {
          id: string
          space_id: string
          email: string
          role: string
          token_hash: string
          status: string
          invited_by: string
          expires_at: string
          accepted_at: string | null
          accepted_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          space_id: string
          email: string
          role?: string
          token_hash: string
          status?: string
          invited_by: string
          expires_at?: string
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          email?: string
          role?: string
          token_hash?: string
          status?: string
          invited_by?: string
          expires_at?: string
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'space_invitations_accepted_by_fkey'
            columns: ['accepted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'space_invitations_invited_by_fkey'
            columns: ['invited_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'space_invitations_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
        ]
      }
      transactions: {
        Row: {
          id: string
          space_id: string
          type: string
          status: string
          amount_cents: number
          occurred_on: string
          description: string
          merchant: string | null
          notes: string | null
          category_id: string | null
          account_id: string | null
          card_id: string | null
          transfer_account_id: string | null
          member_id: string
          created_by: string
          scope: string
          visibility: string
          source: string
          source_ref: string | null
          installment_group_id: string | null
          installment_number: number | null
          installment_count: number | null
          installment_total_cents: number | null
          recurring_rule_id: string | null
          recurring_occurrence_on: string | null
          deleted_at: string | null
          deleted_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          space_id: string
          type: string
          status?: string
          amount_cents: number
          occurred_on: string
          description: string
          merchant?: string | null
          notes?: string | null
          category_id?: string | null
          account_id?: string | null
          card_id?: string | null
          transfer_account_id?: string | null
          member_id: string
          created_by: string
          scope?: string
          visibility?: string
          source?: string
          source_ref?: string | null
          installment_group_id?: string | null
          installment_number?: number | null
          installment_count?: number | null
          installment_total_cents?: number | null
          recurring_rule_id?: string | null
          recurring_occurrence_on?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          space_id?: string
          type?: string
          status?: string
          amount_cents?: number
          occurred_on?: string
          description?: string
          merchant?: string | null
          notes?: string | null
          category_id?: string | null
          account_id?: string | null
          card_id?: string | null
          transfer_account_id?: string | null
          member_id?: string
          created_by?: string
          scope?: string
          visibility?: string
          source?: string
          source_ref?: string | null
          installment_group_id?: string | null
          installment_number?: number | null
          installment_count?: number | null
          installment_total_cents?: number | null
          recurring_rule_id?: string | null
          recurring_occurrence_on?: string | null
          deleted_at?: string | null
          deleted_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'transactions_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'transactions_deleted_by_fkey'
            columns: ['deleted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'transactions_recurring_rule_id_fkey'
            columns: ['recurring_rule_id']
            isOneToOne: false
            referencedRelation: 'recurring_rules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'transactions_space_id_account_id_fkey'
            columns: ['space_id', 'account_id']
            isOneToOne: false
            referencedRelation: 'accounts'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'transactions_space_id_card_id_fkey'
            columns: ['space_id', 'card_id']
            isOneToOne: false
            referencedRelation: 'cards'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'transactions_space_id_category_id_fkey'
            columns: ['space_id', 'category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['space_id', 'id']
          },
          {
            foreignKeyName: 'transactions_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'transactions_space_id_member_id_fkey'
            columns: ['space_id', 'member_id']
            isOneToOne: false
            referencedRelation: 'financial_space_members'
            referencedColumns: ['space_id', 'user_id']
          },
          {
            foreignKeyName: 'transactions_space_id_transfer_account_id_fkey'
            columns: ['space_id', 'transfer_account_id']
            isOneToOne: false
            referencedRelation: 'accounts'
            referencedColumns: ['space_id', 'id']
          },
        ]
      }
      whatsapp_identities: {
        Row: {
          id: string
          user_id: string
          phone_e164: string
          status: string
          default_space_id: string | null
          verification_code_hash: string | null
          verification_expires_at: string | null
          verification_attempts: number
          verified_at: string | null
          revoked_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          phone_e164: string
          status?: string
          default_space_id?: string | null
          verification_code_hash?: string | null
          verification_expires_at?: string | null
          verification_attempts?: number
          verified_at?: string | null
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          phone_e164?: string
          status?: string
          default_space_id?: string | null
          verification_code_hash?: string | null
          verification_expires_at?: string | null
          verification_attempts?: number
          verified_at?: string | null
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'whatsapp_identities_default_space_id_fkey'
            columns: ['default_space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_identities_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      whatsapp_messages: {
        Row: {
          id: string
          direction: string
          wa_message_id: string | null
          identity_id: string | null
          user_id: string | null
          space_id: string | null
          sender_hash: string | null
          message_type: string
          status: string
          content: string | null
          content_expires_at: string | null
          media_id: string | null
          intent: Json | null
          error_code: string | null
          correlation_id: string
          reply_to_id: string | null
          transaction_id: string | null
          wa_timestamp: string | null
          received_at: string
          processed_at: string | null
          attempts: number
          created_at: string
        }
        Insert: {
          id?: string
          direction: string
          wa_message_id?: string | null
          identity_id?: string | null
          user_id?: string | null
          space_id?: string | null
          sender_hash?: string | null
          message_type: string
          status: string
          content?: string | null
          content_expires_at?: string | null
          media_id?: string | null
          intent?: Json | null
          error_code?: string | null
          correlation_id?: string
          reply_to_id?: string | null
          transaction_id?: string | null
          wa_timestamp?: string | null
          received_at?: string
          processed_at?: string | null
          attempts?: number
          created_at?: string
        }
        Update: {
          id?: string
          direction?: string
          wa_message_id?: string | null
          identity_id?: string | null
          user_id?: string | null
          space_id?: string | null
          sender_hash?: string | null
          message_type?: string
          status?: string
          content?: string | null
          content_expires_at?: string | null
          media_id?: string | null
          intent?: Json | null
          error_code?: string | null
          correlation_id?: string
          reply_to_id?: string | null
          transaction_id?: string | null
          wa_timestamp?: string | null
          received_at?: string
          processed_at?: string | null
          attempts?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'whatsapp_messages_identity_id_fkey'
            columns: ['identity_id']
            isOneToOne: false
            referencedRelation: 'whatsapp_identities'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_messages_reply_to_id_fkey'
            columns: ['reply_to_id']
            isOneToOne: false
            referencedRelation: 'whatsapp_messages'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_messages_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_messages_transaction_id_fkey'
            columns: ['transaction_id']
            isOneToOne: false
            referencedRelation: 'transactions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_messages_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      whatsapp_pending_actions: {
        Row: {
          id: string
          identity_id: string
          space_id: string
          user_id: string
          kind: string
          payload: Json
          message_id: string | null
          status: string
          expires_at: string
          created_at: string
          resolved_at: string | null
        }
        Insert: {
          id?: string
          identity_id: string
          space_id: string
          user_id: string
          kind: string
          payload: Json
          message_id?: string | null
          status?: string
          expires_at?: string
          created_at?: string
          resolved_at?: string | null
        }
        Update: {
          id?: string
          identity_id?: string
          space_id?: string
          user_id?: string
          kind?: string
          payload?: Json
          message_id?: string | null
          status?: string
          expires_at?: string
          created_at?: string
          resolved_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'whatsapp_pending_actions_identity_id_fkey'
            columns: ['identity_id']
            isOneToOne: false
            referencedRelation: 'whatsapp_identities'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_pending_actions_message_id_fkey'
            columns: ['message_id']
            isOneToOne: false
            referencedRelation: 'whatsapp_messages'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_pending_actions_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'financial_spaces'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'whatsapp_pending_actions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      goals_with_progress: {
        Row: {
          id: string | null
          space_id: string | null
          name: string | null
          target_amount_cents: number | null
          target_date: string | null
          status: string | null
          scope: string | null
          owner_id: string | null
          tone: string | null
          created_by: string | null
          completed_at: string | null
          created_at: string | null
          updated_at: string | null
          current_amount_cents: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      accept_invitation: {
        Args: {
          p_token: string
        }
        Returns: string
      }
      can_edit_transaction: {
        Args: {
          p_space_id: string
          p_scope: string
          p_visibility: string
          p_member_id: string
          p_created_by: string
        }
        Returns: boolean
      }
      can_view_transaction: {
        Args: {
          p_space_id: string
          p_visibility: string
          p_member_id: string
          p_created_by: string
        }
        Returns: boolean
      }
      card_spend_totals: {
        Args: {
          p_space_id: string
          p_from: string
          p_to: string
        }
        Returns: {
          card_id: string
          total_cents: number
          tx_count: number
        }[]
      }
      complete_onboarding: {
        Args: {
          p_full_name: string
          p_space_name: string
          p_space_type: string
          p_expected_income_cents?: number
          p_plan_mode?: string
          p_group_percents?: Json
          p_category_keys?: string[]
        }
        Returns: string
      }
      copy_monthly_plan: {
        Args: {
          p_space_id: string
          p_from_month: string
          p_to_month: string
        }
        Returns: string
      }
      create_invitation: {
        Args: {
          p_space_id: string
          p_email: string
          p_role?: string
        }
        Returns: {
          invitation_id: string
          token: string
          expires_at: string
        }[]
      }
      get_invitation_preview: {
        Args: {
          p_token: string
        }
        Returns: {
          space_name: string
          inviter_name: string
          email_hint: string
          status: string
          expires_at: string
        }[]
      }
      is_space_admin: {
        Args: {
          p_space_id: string
        }
        Returns: boolean
      }
      is_space_member: {
        Args: {
          p_space_id: string
        }
        Returns: boolean
      }
      purge_expired_data: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      remove_space_member: {
        Args: {
          p_space_id: string
          p_user_id: string
        }
        Returns: undefined
      }
      revoke_invitation: {
        Args: {
          p_invitation_id: string
        }
        Returns: undefined
      }
      revoke_whatsapp_identity: {
        Args: {
          p_identity_id: string
        }
        Returns: undefined
      }
      seed_space_defaults: {
        Args: {
          p_space_id: string
          p_category_keys?: string[]
        }
        Returns: undefined
      }
      set_whatsapp_default_space: {
        Args: {
          p_identity_id: string
          p_space_id: string
        }
        Returns: undefined
      }
      shares_space_with: {
        Args: {
          p_user_id: string
        }
        Returns: boolean
      }
      space_category_totals: {
        Args: {
          p_space_id: string
          p_from: string
          p_to: string
          p_member_id?: string
          p_scope?: string
        }
        Returns: {
          category_id: string
          type: string
          total_cents: number
          tx_count: number
        }[]
      }
      space_category_totals_as: {
        Args: {
          p_viewer: string
          p_space_id: string
          p_from: string
          p_to: string
        }
        Returns: {
          category_id: string
          type: string
          total_cents: number
          tx_count: number
        }[]
      }
      space_monthly_totals: {
        Args: {
          p_space_id: string
          p_from: string
          p_to: string
          p_member_id?: string
          p_scope?: string
        }
        Returns: {
          month: string
          income_cents: number
          expense_cents: number
          savings_cents: number
        }[]
      }
      space_role: {
        Args: {
          p_space_id: string
        }
        Returns: string
      }
      start_whatsapp_link: {
        Args: {
          p_phone_e164: string
          p_space_id: string
        }
        Returns: {
          identity_id: string
          code: string
          expires_at: string
          status: string
        }[]
      }
      upsert_monthly_plan: {
        Args: {
          p_space_id: string
          p_month: string
          p_expected_income_cents: number
          p_groups: Json
          p_categories: Json
        }
        Returns: string
      }
      verify_whatsapp_link: {
        Args: {
          p_phones: string[]
          p_code: string
        }
        Returns: {
          status: string
          identity_id: string
          user_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database['public']
export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row']
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update']
export type Views<T extends keyof PublicSchema['Views']> = PublicSchema['Views'][T]['Row']
