/**
 * Generates src/types/database.types.ts by introspecting a database that has the migrations
 * applied (local test cluster by default). Output follows the `supabase gen types typescript`
 * format, so it can be replaced by the official generator at any time:
 *   supabase gen types typescript --project-id <id> > src/types/database.types.ts
 *
 *   npm run db:local && npm run db:types
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import pg from 'pg'

const ADMIN_URL = process.env.PRUMO_TEST_DATABASE_URL ?? 'postgres://postgres@127.0.0.1:54329/postgres'
const DB = 'prumo_types'

const PG_TO_TS: Record<string, string> = {
  uuid: 'string',
  text: 'string',
  bpchar: 'string',
  varchar: 'string',
  citext: 'string',
  date: 'string',
  timestamptz: 'string',
  timestamp: 'string',
  int2: 'number',
  int4: 'number',
  int8: 'number',
  numeric: 'number',
  float4: 'number',
  float8: 'number',
  bool: 'boolean',
  jsonb: 'Json',
  json: 'Json',
  bytea: 'string',
  void: 'undefined',
}

function tsType(udt: string): string {
  if (udt.startsWith('_')) return `${tsType(udt.slice(1))}[]`
  return PG_TO_TS[udt] ?? 'unknown'
}

async function main() {
  const admin = new pg.Client({ connectionString: ADMIN_URL })
  await admin.connect()
  await admin.query(`drop database if exists ${DB} with (force)`)
  await admin.query(`create database ${DB}`)
  await admin.end()

  const url = new URL(ADMIN_URL)
  url.pathname = `/${DB}`
  const client = new pg.Client({ connectionString: url.toString() })
  await client.connect()
  const root = process.cwd()
  await client.query(readFileSync(join(root, 'tests/db/supabase-stub.sql'), 'utf8'))
  const dir = join(root, 'supabase/migrations')
  for (const f of readdirSync(dir).filter((x) => x.endsWith('.sql')).sort()) {
    await client.query(readFileSync(join(dir, f), 'utf8'))
  }

  const columns = (
    await client.query(`
      select c.table_name, c.column_name, c.udt_name, c.is_nullable = 'YES' as nullable,
             (c.column_default is not null or c.is_identity = 'YES' or c.is_generated = 'ALWAYS') as has_default,
             c.is_generated = 'ALWAYS' or c.identity_generation = 'ALWAYS' as generated,
             t.table_type
      from information_schema.columns c
      join information_schema.tables t on t.table_schema = c.table_schema and t.table_name = c.table_name
      where c.table_schema = 'public'
      order by c.table_name, c.ordinal_position`)
  ).rows

  const fks = (
    await client.query(`
      select con.conname, rel.relname as table_name, frel.relname as ref_table,
             array(select att.attname::text from unnest(con.conkey) with ordinality k(num, ord)
                   join pg_attribute att on att.attrelid = con.conrelid and att.attnum = k.num order by k.ord) as cols,
             array(select att.attname::text from unnest(con.confkey) with ordinality k(num, ord)
                   join pg_attribute att on att.attrelid = con.confrelid and att.attnum = k.num order by k.ord) as ref_cols
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_class frel on frel.oid = con.confrelid
      join pg_namespace n on n.oid = rel.relnamespace
      join pg_namespace fn on fn.oid = frel.relnamespace
      where con.contype = 'f' and n.nspname = 'public' and fn.nspname = 'public'
      order by rel.relname, con.conname`)
  ).rows

  const functions = (
    await client.query(`
      select p.proname, p.proargnames::text[] as proargnames, p.proargmodes::text[] as proargmodes,
             array(select tt.typname::text from unnest(p.proargtypes::oid[]) with ordinality a(oid, ord)
                   join pg_type tt on tt.oid = a.oid order by a.ord) as arg_types,
             array(select tt.typname::text from unnest(p.proallargtypes) with ordinality a(oid, ord)
                   join pg_type tt on tt.oid = a.oid order by a.ord) as all_types,
             p.pronargdefaults, p.proretset, rt.typname::text as ret_type
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      join pg_type rt on rt.oid = p.prorettype
      where n.nspname = 'public' and p.prokind = 'f' and rt.typname <> 'trigger'
      order by p.proname`)
  ).rows
  await client.end()

  const tables = new Map<string, typeof columns>()
  const views = new Map<string, typeof columns>()
  for (const col of columns) {
    const bucket = col.table_type === 'VIEW' ? views : tables
    bucket.set(col.table_name, [...(bucket.get(col.table_name) ?? []), col])
  }

  const lines: string[] = []
  const w = (s: string) => lines.push(s)
  w('// GENERATED by scripts/generate-db-types.ts — do not edit by hand.')
  w('// Format-compatible with `supabase gen types typescript`.')
  w('')
  w('export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]')
  w('')
  w('export type Database = {')
  w('  __InternalSupabase: {')
  w("    PostgrestVersion: '12.2.3'")
  w('  }')
  w('  public: {')
  w('    Tables: {')
  for (const [name, cols] of tables) {
    w(`      ${name}: {`)
    w('        Row: {')
    for (const c of cols) w(`          ${c.column_name}: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''}`)
    w('        }')
    w('        Insert: {')
    for (const c of cols) {
      if (c.generated) continue
      const optional = c.nullable || c.has_default
      w(`          ${c.column_name}${optional ? '?' : ''}: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''}`)
    }
    w('        }')
    w('        Update: {')
    for (const c of cols) {
      if (c.generated) continue
      w(`          ${c.column_name}?: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''}`)
    }
    w('        }')
    w('        Relationships: [')
    for (const fk of fks.filter((f) => f.table_name === name)) {
      w('          {')
      w(`            foreignKeyName: '${fk.conname}'`)
      w(`            columns: [${fk.cols.map((c: string) => `'${c}'`).join(', ')}]`)
      w('            isOneToOne: false')
      w(`            referencedRelation: '${fk.ref_table}'`)
      w(`            referencedColumns: [${fk.ref_cols.map((c: string) => `'${c}'`).join(', ')}]`)
      w('          },')
    }
    w('        ]')
    w('      }')
  }
  w('    }')
  w('    Views: {')
  for (const [name, cols] of views) {
    w(`      ${name}: {`)
    w('        Row: {')
    for (const c of cols) w(`          ${c.column_name}: ${tsType(c.udt_name)} | null`)
    w('        }')
    w('        Relationships: []')
    w('      }')
  }
  w('    }')
  w('    Functions: {')
  for (const fn of functions) {
    const names: string[] = fn.proargnames ?? []
    const modes: string[] | null = fn.proargmodes
    const allTypes: string[] = fn.all_types ?? []
    const inArgs: { name: string; type: string }[] = []
    const outCols: { name: string; type: string }[] = []
    if (modes) {
      modes.forEach((mode, i) => {
        const entry = { name: names[i] ?? `arg${i}`, type: tsType(allTypes[i] ?? 'unknown') }
        if (mode === 'i' || mode === 'b') inArgs.push(entry)
        if (mode === 't' || mode === 'o' || mode === 'b') outCols.push(entry)
      })
    } else {
      ;(fn.arg_types as string[]).forEach((udt, i) => {
        inArgs.push({ name: names[i] ?? `arg${i}`, type: tsType(udt) })
      })
    }
    const defaults = Number(fn.pronargdefaults)
    w(`      ${fn.proname}: {`)
    if (inArgs.length === 0) w('        Args: Record<PropertyKey, never>')
    else {
      w('        Args: {')
      inArgs.forEach((a, i) => w(`          ${a.name}${i >= inArgs.length - defaults ? '?' : ''}: ${a.type}`))
      w('        }')
    }
    if (outCols.length > 0) {
      w('        Returns: {')
      for (const o of outCols) w(`          ${o.name}: ${o.type}`)
      w('        }[]')
    } else {
      w(`        Returns: ${tsType(fn.ret_type)}${fn.proretset ? '[]' : ''}`)
    }
    w('      }')
  }
  w('    }')
  w('    Enums: {')
  w('      [_ in never]: never')
  w('    }')
  w('    CompositeTypes: {')
  w('      [_ in never]: never')
  w('    }')
  w('  }')
  w('}')
  w('')
  w("type PublicSchema = Database['public']")
  w("export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row']")
  w("export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert']")
  w("export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update']")
  w("export type Views<T extends keyof PublicSchema['Views']> = PublicSchema['Views'][T]['Row']")
  w('')

  const target = resolve(root, 'src/types/database.types.ts')
  writeFileSync(target, lines.join('\n'))
  console.log(`types written: ${target} (${tables.size} tables, ${views.size} views, ${functions.length} functions)`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
