/**
 * Generates supabase/seed.sql from the single dev dataset (src/server/data/demo/dataset.ts).
 *   npm run db:seed:generate
 * The SQL keeps dates relative to current_date, so a fresh `supabase db reset` always
 * produces a "current" month.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  DEMO_ACCOUNTS,
  DEMO_CARDS,
  DEMO_GOALS,
  DEMO_PASSWORD,
  DEMO_PLANS,
  DEMO_RECURRING,
  DEMO_SPACE,
  DEMO_USERS,
  demoTransactions,
} from '../src/server/data/demo/dataset'
import { demoId } from '../src/server/data/demo/ids'

const q = (v: string | null | undefined) => (v === null || v === undefined ? 'null' : `'${v.replace(/'/g, "''")}'`)
const uid = (member: keyof typeof DEMO_USERS | null | undefined) => (member ? q(DEMO_USERS[member].id) : 'null')
const space = q(DEMO_SPACE.id)
const cat = (key: string) => `(select id from public.categories where space_id = ${space} and system_key = ${q(key)})`
const grp = (key: string) => `(select id from public.category_groups where space_id = ${space} and key = ${q(key)})`

const lines: string[] = []
const out = (s = '') => lines.push(s)

out('-- ============================================================================')
out('-- PRUMO · DEV SEED — fictitious data for local development only.')
out('-- GENERATED by scripts/generate-seed.ts from src/server/data/demo/dataset.ts.')
out('-- Do not edit by hand. Never run against production.')
out(`-- Users: ${DEMO_USERS.lucas.email} / ${DEMO_USERS.marina.email} — password: ${DEMO_PASSWORD}`)
out('-- ============================================================================')
out()
out('begin;')
out()
out(`create function pg_temp.demo_date(p_m int, p_d int) returns date language sql stable as $$
  select (s.m + (least(p_d, extract(day from (s.m + interval '1 month - 1 day'))::int) - 1))::date
  from (select (date_trunc('month', current_date) + make_interval(months => p_m))::date as m) s
$$;`)
out(`create function pg_temp.demo_next(p_d int) returns date language sql stable as $$
  select case when pg_temp.demo_date(0, p_d) > current_date then pg_temp.demo_date(0, p_d) else pg_temp.demo_date(1, p_d) end
$$;`)
out()

out('-- Users (auth) → profiles are created by the on_auth_user_created trigger')
for (const user of Object.values(DEMO_USERS)) {
  out(`insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', ${q(user.id)}, 'authenticated', 'authenticated', ${q(user.email)},
  extensions.crypt(${q(DEMO_PASSWORD)}, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', ${q(JSON.stringify({ full_name: user.fullName }))}, now(), now(), '', '', '', '')
on conflict (id) do nothing;`)
  out(`insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), ${q(user.id)}, ${q(user.id)}, ${q(JSON.stringify({ sub: user.id, email: user.email, email_verified: true }))}::jsonb, 'email', now(), now(), now())
on conflict do nothing;`)
}
out()

out('-- Shared financial space')
out(`insert into public.financial_spaces (id, name, type, owner_id, plan_code)
values (${space}, ${q(DEMO_SPACE.name)}, ${q(DEMO_SPACE.type)}, ${uid(DEMO_SPACE.owner)}, 'premium');`)
out(`insert into public.financial_space_members (space_id, user_id, role, joined_at) values
  (${space}, ${uid('lucas')}, 'owner', now() - interval '10 months'),
  (${space}, ${uid('marina')}, 'admin', now() - interval '10 months');`)
out(`select public.seed_space_defaults(${space}, null);`)
for (const user of Object.values(DEMO_USERS)) {
  out(`update public.profiles set full_name = ${q(user.fullName)}, onboarded_at = now(), default_space_id = ${space} where id = ${q(user.id)};`)
}
out()

out('-- Accounts & cards (metadata only)')
for (const a of Object.values(DEMO_ACCOUNTS)) {
  out(`insert into public.accounts (id, space_id, name, type, opening_balance_cents, owner_id, sort_order)
values (${q(a.id)}, ${space}, ${q(a.name)}, ${q(a.type)}, ${a.openingBalanceCents}, ${uid(a.owner)}, ${a.sortOrder});`)
}
for (const c of Object.values(DEMO_CARDS)) {
  out(`insert into public.cards (id, space_id, name, last_four, closing_day, due_day, limit_cents, holder_id, tone)
values (${q(c.id)}, ${space}, ${q(c.name)}, ${q(c.lastFour)}, ${c.closingDay}, ${c.dueDay}, ${c.limitCents}, ${uid(c.holder)}, ${q(c.tone)});`)
}
out()

out('-- Recurring rules')
for (const r of Object.values(DEMO_RECURRING)) {
  out(`insert into public.recurring_rules (id, space_id, type, description, amount_cents, category_id, account_id, card_id, member_id, scope,
  frequency, start_on, next_occurrence_on, created_by)
values (${q(r.id)}, ${space}, ${q(r.type)}, ${q(r.description)}, ${r.amountCents}, ${cat(r.category)},
  ${r.account ? q(DEMO_ACCOUNTS[r.account]!.id) : 'null'}, ${r.card ? q(DEMO_CARDS[r.card]!.id) : 'null'}, ${uid(r.member)}, ${q(r.scope)},
  ${q(r.frequency)}, pg_temp.demo_date(-6, ${r.day}), pg_temp.demo_next(${r.day}), ${uid(r.member)});`)
}
out()

out('-- Transactions (current month only up to today; future installments are real commitments)')
const txs = demoTransactions()
const rows = txs.map((t) => {
  const inst = t.installment
  return `  (${t.m}, ${t.d}, ${q(t.type)}, ${t.amountCents}, ${q(t.description)}, ${q(t.merchant)}, ${q(t.category)}, ${uid(t.member)}, ${q(t.scope)}, ${q(t.visibility ?? 'space')}, ${t.account ? q(DEMO_ACCOUNTS[t.account]!.id) : 'null'}::uuid, ${t.card ? q(DEMO_CARDS[t.card]!.id) : 'null'}::uuid, ${q(t.source ?? 'dashboard')}, ${t.recurring ? q(DEMO_RECURRING[t.recurring]!.id) : 'null'}::uuid, ${inst ? q(demoId(`installment:${inst.key}`)) : 'null'}::uuid, ${inst ? inst.number : 'null'}::smallint, ${inst ? inst.count : 'null'}::smallint, ${inst ? inst.totalCents : 'null'}::bigint)`
})
out(`insert into public.transactions (space_id, type, amount_cents, occurred_on, description, merchant, category_id, member_id, created_by,
  scope, visibility, account_id, card_id, source, recurring_rule_id, recurring_occurrence_on,
  installment_group_id, installment_number, installment_count, installment_total_cents, created_at)
select ${space}, r.type, r.amount, pg_temp.demo_date(r.m, r.d), r.description, r.merchant,
  (select id from public.categories c where c.space_id = ${space} and c.system_key = r.cat),
  r.member::uuid, r.member::uuid, r.scope, r.visibility, r.account_id, r.card_id, r.source,
  r.rule_id, case when r.rule_id is not null then pg_temp.demo_date(r.m, r.d) end,
  r.inst_group, r.inst_no, r.inst_count, r.inst_total, least(pg_temp.demo_date(r.m, r.d)::timestamptz + interval '12 hours', now() - interval '3 hours')
from (values
${rows.join(',\n')}
) as r(m, d, type, amount, description, merchant, cat, member, scope, visibility, account_id, card_id, source, rule_id, inst_group, inst_no, inst_count, inst_total)
where pg_temp.demo_date(r.m, r.d) <= current_date or r.inst_group is not null;`)
out()

out('-- Monthly plans (custom split 50/35/15 — the product only suggests 50/40/10)')
for (const p of DEMO_PLANS) {
  const planId = demoId(`plan:${p.m}`)
  out(`insert into public.monthly_plans (id, space_id, month, expected_income_cents, created_by)
values (${q(planId)}, ${space}, date_trunc('month', pg_temp.demo_date(${p.m}, 1))::date, ${p.expectedIncomeCents}, ${uid('lucas')});`)
  for (const g of p.groups) {
    out(`insert into public.plan_group_budgets (plan_id, space_id, group_id, mode, percent_bp) values (${q(planId)}, ${space}, ${grp(g.key)}, 'percent', ${g.percentBp});`)
  }
  for (const c of p.categories) {
    out(`insert into public.plan_category_budgets (plan_id, space_id, category_id, amount_cents) values (${q(planId)}, ${space}, ${cat(c.key)}, ${c.amountCents});`)
  }
}
out()

out('-- Goals')
for (const g of DEMO_GOALS) {
  out(`insert into public.goals (id, space_id, name, target_amount_cents, target_date, status, scope, owner_id, tone, created_by, created_at, completed_at)
values (${q(g.id)}, ${space}, ${q(g.name)}, ${g.targetAmountCents}, pg_temp.demo_date(${g.targetMonthOffset}, 28), ${q('completed' in g && g.completed ? 'completed' : 'active')},
  ${q(g.scope)}, ${uid(g.owner)}, ${q(g.tone)}, ${uid('lucas')}, pg_temp.demo_date(${g.createdMonthOffset}, 1)::timestamptz, ${'completed' in g && g.completed ? `pg_temp.demo_date(${g.targetMonthOffset}, 28)::timestamptz` : 'null'});`)
  for (const c of g.contributions) {
    out(`insert into public.goal_contributions (goal_id, space_id, amount_cents, contributed_on, note, created_by)
select ${q(g.id)}, ${space}, ${c.amountCents}, pg_temp.demo_date(${c.m}, ${c.d}), ${q('note' in c ? c.note : null)}, ${uid('lucas')}
where pg_temp.demo_date(${c.m}, ${c.d}) <= current_date;`)
  }
}
out()

out('-- WhatsApp identities (fictitious numbers, already verified) — use them in the local simulator')
for (const [key, user] of Object.entries(DEMO_USERS)) {
  out(`insert into public.whatsapp_identities (id, user_id, phone_e164, status, default_space_id, verified_at)
values (${q(demoId(`wa-identity:${key}`))}, ${q(user.id)}, ${q(user.phone)}, 'verified', ${space}, now());`)
}
out()
out('commit;')
out()

const target = resolve(process.cwd(), 'supabase/seed.sql')
writeFileSync(target, lines.join('\n'))
console.log(`seed written: ${target} (${txs.length} transaction templates)`)
